### ISSUE TITLE
Criação de arquivo  CONTRIBUTING.md 

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Livro-FMC#1]
Atualmente não há informações de como poderia ser feito o build do pdf para que o leitor passa contribuir ou compilar novas versões. Poderia ser criado o arquivo `CONTRIBUTING.md` com comandos relevantes para fazer o build do pdf.

**Comment by valdigleis** [comment]
A ideia é que leitor aponte erros no texto ou sugestões para temas a serem desenvolvidos no manuscrito. Como qualquer **projeto de livro aberto** (_open book_) este projeto não tem por natureza que o mesmo (o leitor) venha a implementar nada neste manuscrito, se o leitor quiser fazer algo assim, ele é livre pela licença adotada neste projeto a clonar o mesmo e fazer seu próprio desenvolvimento a partir dai suas ideias, desde que mantenha os créditos aos autores das partes que não são dele, dessa forma não é necessário arquivos de CONTRIBUTING.md

**Comment by raulpy271** [comment]
Faz sentido. Então eu me expresei mal, na verdade, não era necessariamente o arquivo CONTRIBUTING.md que senti falta, e sim informações de como compilar o código para gerar o pdf.

**Comment by valdigleis** [comment]
Então Raul, criei um arquivo Makefile para gerar o projeto. Na sua opinião de "público alvo" do manuscrito, eu devo colocar uma explicação de como executar o arquivo Makefile no README?

**Comment by raulpy271** [comment]
Boa Valdi. Agora ficou claro! Eu acho opcional, porque só a presença do Makefile já mostra os comandos necessários.

**Comment by valdigleis** [comment]
Ok!
