### ISSUE TITLE
Erro de escrita

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Livro-FMC#2]
Na linha 45 do arquivo `capComp/capIntro.tex` esta escrito:

> ... a própria ideia de procedimento efetivo é algo quase que inerente a intuição humana mas que é extremamente complexa (**e possível impossível**) de se formalizar em termos matemáticos precisos.

Não seria "e possivelmente impossível"?

**Comment by valdigleis** [comment]
Exatamente! 

Obrigado pela dica.... Já corrigido!
