### ISSUE TITLE
Erro em exercício 10.18

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Livro-FMC#3]
![Screenshot from 2022-01-14 22-23-42](https://user-images.githubusercontent.com/56479285/149633253-b32ab056-f9fd-4853-a19a-db7e03232b94.png)
Ao invés de ser "m menor ou igual 1", não seria "m maior ou igual a 1"?

**Comment by valdigleis** [comment]
Seria realmente maior igual... Novamente corrigido!
