### ISSUE TITLE
Duvida sobre demonstração do exemplo 10.24

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Livro-FMC#4]
Nesta [linha](https://github.com/valdigleis/Livro-FMC/blob/7c88c04506fdd276091babd6a9be2a1dab27cd80/capComp/capLRegulares.tex#L619), está escrito:

> \item Já o acesso via $q_4$ só é permitido se antes o autômato conseguir acessar o estado $q_4$, ...

O correto seria:

> \item Já o acesso via $q_4$ só é permitido se antes o autômato conseguir acessar o estado $q_2$, ...

O que acha?

**Comment by valdigleis** [comment]
Feito a correção, e melhorei um pouco o texto!
