### ISSUE TITLE
Erro de escrita em exemplo 10.36

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Livro-FMC#5]
Neste [exemplo](https://github.com/valdigleis/Livro-FMC/blob/7c88c04506fdd276091babd6a9be2a1dab27cd80/capComp/capLRegulares.tex#L1151), é dito:

> Considere o $\lambda$-AFN da Figura \ref{fig:LAFN1} tem-se para o estado $q_0$ que,

Eu imagino que ao invés de `$q_0$`, o senhor quis dizer `$q_1$`.

Neste mesmo exemplo, o senhor escreve:

> desenvolvendo $q' \in \lambda\text{-fecho}^{1}(q_0)$ tem-se que,

Imagino, mais uma vez, que ao invés de `$q_0$` seria `$q_1$`. O que acha?

**Comment by valdigleis** [comment]
Corrigido também!!!!
