### ISSUE TITLE
Dúvida sobre definição do automato da figura 10.13

### ISSUE THREAD

**Issue by raulpy271** [valdigleis/Livro-FMC#6]
![ex-10 39](https://user-images.githubusercontent.com/56479285/149674819-090400a8-c162-43b7-9a0a-21aa4fad9012.png)

Pra mim surgiu uma dúvida sobre a definição do automato a cima, segundo o manuscrito, o automato aceitaria a palavra `11233`. Que é uma palavra da linguagem `L`, no entanto, ao fazer a computação do automato dessa palavra, obtemos o estado `{s2}`, que não é um estado final, isto é uma contradição, concorda?

**Comment by valdigleis** [comment]
Você tem razão não notei e inverti tudo, no caso só s2 deve ser final!
